[package]
name = "monitormenu"
version = "0.1.0"
edition = "2021"
authors = ["monitormenu contributors"]
description = "Launcher-driven monitor manager for Hyprland"
license = "GPL-3.0"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
